listing:
    resource: "@ListingBundle/Controller/"
    type:     annotation
    prefix:   /

boutique:
    resource: "@BoutiqueBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
